In [1]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info

<bound method DataFrame.info of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [5]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [15]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [24]:
#create a column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [25]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [27]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [28]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [29]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [30]:

(df['discount_applied'] == df['promo_code_used']).all()

True

In [31]:

# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [32]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [36]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\harsh\anaconda3\anaconda\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\harsh\anaconda3\anaconda\lib\site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\harsh\anaconda3\anaconda\lib\site-packages (from sqlalchemy) (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [37]:
!pip install pymysql pandas

Collecting pymysql
  Obtaining dependency information for pymysql from https://files.pythonhosted.org/packages/7c/4c/ad33b92b9864cbde84f259d5df035a6447f91891f5be77788e2a3892bce3/pymysql-1.1.2-py3-none-any.whl.metadata
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: pandas in c:\users\harsh\anaconda3\anaconda\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harsh\anaconda3\anaconda\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\harsh\anaconda3\anaconda\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\harsh\anaconda3\anaconda\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\harsh\anaconda3\anaconda\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\harsh\anaconda3\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.3 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.3 kB ? eta -:--:--
   ------------------------------------ --- 41.0/45.3 kB 393.8 kB/s eta 0:00:01
   ---------------------------------------- 45.3/45.3 kB 280.5 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [39]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/3f/99/da0f55beb970ca049fd7d37a6391d686222af89a8b13e636d8e9bbd06536/mysql_connector_python-9.6.0-cp311-cp311-win_amd64.whl.metadata
  Downloading mysql_connector_python-9.6.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp311-cp311-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB 162.5 kB/s eta 0:01:42
   ---------------------------------------- 0.0/16.5 MB 245.8 kB/s eta 0:01:08
   ---------------------------------------- 0.1/16.5 MB 328.2 kB/s eta 0:00:51
   ---------------------------------------- 0.1/16.5 MB 554.9 kB/s eta 0:00:30
    --------------------------------------- 0.3/16.5 MB 923.9 kB/s eta 0:00:18
   - -------------------------------------- 0.4/16.5 MB 1.3 MB/s eta 0:00:13
   - -------------------------------------- 0.7/16.5 MB 1.8 MB/s eta 0:00:09
   -- ------------------------------------- 0.9/16.5 MB 2.2 MB/s eta 0:00:08
   -- ------------------------------------- 1.2/16.5 MB 2.6 MB/s eta 0:00:06
   --- ------------------------------------ 1.5/16.5 MB 2.8 MB/s eta 0:00:06
   ---- ----------------------------------- 1.8/16.5 MB 3.1 MB/s eta 0:00:05
   ---- ----------------------------------- 2.0/16.5 MB 3.2 MB/s eta 0:00:05
   ----- ---------------------------------- 2.3/16.5 MB 3.4 MB/s eta 0:00:05
   ------ --------------------------------- 2.5/16.5 MB 3.6 MB/s eta 0:00:04
   ------ --------------------------------- 2.8/16.5 MB 3.7 MB/s eta 0:00:04
   ------- -------------------------------- 3.1/16.5 MB 3.8 MB/s eta 0:00:04
   -------- ------------------------------- 3.3/16.5 MB 3.9 MB/s eta 0:00:04
   -------- ------------------------------- 3.6/16.5 MB 3.9 MB/s eta 0:00:04
   --------- ------------------------------ 3.8/16.5 MB 3.9 MB/s eta 0:00:04
   --------- ------------------------------ 4.0/16.5 MB 3.9 MB/s eta 0:00:04
   ---------- ----------------------------- 4.5/16.5 MB 4.1 MB/s eta 0:00:03
   ----------- ---------------------------- 4.9/16.5 MB 4.2 MB/s eta 0:00:03
   ------------ --------------------------- 5.4/16.5 MB 4.5 MB/s eta 0:00:03
   ------------- -------------------------- 5.7/16.5 MB 4.6 MB/s eta 0:00:03
   --------------- ------------------------ 6.2/16.5 MB 4.8 MB/s eta 0:00:03
   --------------- ------------------------ 6.6/16.5 MB 4.9 MB/s eta 0:00:03
   ---------------- ----------------------- 6.8/16.5 MB 5.0 MB/s eta 0:00:02
   ----------------- ---------------------- 7.2/16.5 MB 5.1 MB/s eta 0:00:02
   ------------------ --------------------- 7.6/16.5 MB 5.1 MB/s eta 0:00:02
   ------------------- -------------------- 8.0/16.5 MB 5.2 MB/s eta 0:00:02
   -------------------- ------------------- 8.5/16.5 MB 5.4 MB/s eta 0:00:02
   --------------------- ------------------ 8.8/16.5 MB 5.5 MB/s eta 0:00:02
   ---------------------- ----------------- 9.2/16.5 MB 5.6 MB/s eta 0:00:02
   ----------------------- ---------------- 9.6/16.5 MB 5.6 MB/s eta 0:00:02
   ------------------------ --------------- 10.1/16.5 MB 5.7 MB/s eta 0:00:02
   ------------------------- -------------- 10.5/16.5 MB 6.6 MB/s eta 0:00:01
   -------------------------- ------------- 11.0/16.5 MB 7.0 MB/s eta 0:00:01
   --------------------------- ------------ 11.3/16.5 MB 7.0 MB/s eta 0:00:01
   ---------------------------- ----------- 11.8/16.5 MB 7.2 MB/s eta 0:00:01
   ----------------------------- ---------- 12.2/16.5 MB 7.4 MB/s eta 0:00:01
   ------------------------------ --------- 12.5/16.5 MB 7.4 MB/s eta 0:00:01
   ------------------------------- -------- 12.8/16.5 MB 7.4 MB/s eta 0:00:01
   ------------------------------- -------- 13.0/16.5 MB 7.3 MB/s eta 0:00:01
   -------------------------------- ------- 13.3/16.5 MB 7.3 MB/s eta 0:00:01
   -------------------------------- ------- 13.6/16.5 MB 7.4 MB/s eta 0:00:01
   ---------------------------------- ----- 14.1/16.5 MB 7.8 MB/s eta 0:00:01
   ----------------------------------- ---- 14.5/16.5 MB 7.8 MB/s eta 0:00:01
   ----------------------------------- ---- 14.8/16.5 MB 7.8 MB/s eta 0:00:01
   ------------------------------------ --- 14.9/16.5 MB 7.6 MB/s eta 0:00:01
   ------------------------------------ --- 15.2/16.5 MB 7.6 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 7.5 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 7.5 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 7.5 MB/s eta 0:00:01
   -------------------------------------- - 16.1/16.5 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  16.5/16.5 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  16.5/16.5 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  16.5/16.5 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 6.4 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [ ]:
import mysql.connector as msc
import pandas as pd

try:
    conn = msc.connect(
        host="127.0.0.1",      # Your host name
        port=3306,             # Your port number (default is 3306)
        user="root",  # Your MySQL username (default is "root")
        password="Harsh@7007", # Your MySQL password
        database="customer"  # The specific database name you want to use
    )
    if conn.is_connected():
        print("Connection to MySQL DB successful")
except msc.Error as err:
    print(f"Error: {err}")